### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by Twinbird24** [vehikl/vehikl-growth-sessions#82]
"The lumberjack was trying to cut down a tree **with and was** swearing and cursing labouring in vain."
I'm guessing it's supposed to say "...cut down a tree with **a saw** and..."

**Comment by chipit24** [comment]
Could also look into a couple other bits:

> In "The 7 Habits of Highly Effective People" Stephen Covey tells the story of a hiker who was walking through a forest when **they** came across a frustrated lumberjack.

I think it should be **he** instead of **they**, since a single hiker came cross a lumberjack, and not a group. It sounds awkward reading it with a **they**. But it also might be ambiguous if the _he_ refers to the hiker or to Stephen Covey.

> The lumberjack was trying to cut down a tree with and was swearing and cursing labouring in vain.

I also think a comma would come naturally between _cursing_ and _labouring_:

> The lumberjack was trying to cut down a tree with and was swearing and cursing, labouring in vain.

**Comment by chipit24** [comment]
This issue can be closed, it was fixed in https://github.com/vehikl/vehikl-growth-sessions/pull/83.
